/**
 * Source registry + scrapers — Phase 1.
 *
 * The registry below is the seed source list. In Phase 2 it's mirrored into
 * the Supabase `sources` table; the workers read from the table, not from
 * this file. Treat this as the canonical starting point.
 *
 * See docs/ingestion-strategy.md for the strategy this list operationalizes
 * (tiers, fetch cadence, ingestion modes, paywall handling, dedup).
 */

export type SourceCountry = "us" | "uk" | "cn" | "tw" | "hk" | "jp" | "intl";
export type SourceLang = "en" | "zh-cn" | "zh-tw";
export type SourceTier = 1 | 2 | 3 | 4;
export type SourceMode = "rss" | "api" | "scrape" | "social";
export type SourceCategory =
  | "wire"
  | "general"
  | "financial"
  | "defense"
  | "tech"
  | "policy"
  | "think_tank"
  | "government"
  | "social";

export interface Source {
  slug: string;
  display_name: string;
  country: SourceCountry;
  lang: SourceLang;
  tier: SourceTier;
  mode: SourceMode;
  category: SourceCategory;
  url: string;
  /** RSS/Atom feed URL when mode === "rss". */
  rss_url?: string;
  /** Most articles are behind a paywall. UI surfaces a paywall flag. */
  paywall?: boolean;
  enabled: boolean;
  /** Minutes between polls. Defaults follow tier (T1: 15, T2: 15, T3: 30). */
  cadence_min?: number;
  notes?: string;
}

/**
 * SEED_SOURCES — comprehensive starting set. Expand as needed; the registry
 * is intended to grow into the hundreds over time. Each entry below has been
 * checked for currently-published feed URLs at scaffold time; the worker is
 * expected to detect broken feeds and surface them in `/admin/health`.
 */
export const SEED_SOURCES: readonly Source[] = [
  // ────────────────────────────────────────────────────────────────────
  // TIER 1 — Authoritative wires
  // ────────────────────────────────────────────────────────────────────
  {
    slug: "reuters-asia",
    display_name: "Reuters · Asia Pacific",
    country: "intl",
    lang: "en",
    tier: 1,
    mode: "rss",
    category: "wire",
    url: "https://www.reuters.com/world/asia-pacific/",
    rss_url: "https://www.reuters.com/world/asia-pacific/rss",
    enabled: true,
  },
  {
    slug: "reuters-china",
    display_name: "Reuters · China",
    country: "intl",
    lang: "en",
    tier: 1,
    mode: "rss",
    category: "wire",
    url: "https://www.reuters.com/world/china/",
    rss_url: "https://www.reuters.com/world/china/rss",
    enabled: true,
  },
  {
    slug: "ap-asia",
    display_name: "Associated Press · Asia",
    country: "intl",
    lang: "en",
    tier: 1,
    mode: "rss",
    category: "wire",
    url: "https://apnews.com/hub/asia-pacific",
    rss_url: "https://apnews.com/hub/asia-pacific/rss",
    enabled: true,
  },
  {
    slug: "bloomberg-asia",
    display_name: "Bloomberg · Asia",
    country: "intl",
    lang: "en",
    tier: 1,
    mode: "rss",
    category: "wire",
    url: "https://www.bloomberg.com/asia",
    paywall: true,
    enabled: true,
    notes: "RSS limited; structured API preferred via Bloomberg Terminal contract.",
  },
  {
    slug: "ft-asia",
    display_name: "Financial Times · Asia",
    country: "intl",
    lang: "en",
    tier: 1,
    mode: "rss",
    category: "wire",
    url: "https://www.ft.com/world/asia-pacific",
    rss_url: "https://www.ft.com/world/asia-pacific?format=rss",
    paywall: true,
    enabled: true,
  },
  {
    slug: "wsj-china",
    display_name: "Wall Street Journal · China",
    country: "intl",
    lang: "en",
    tier: 1,
    mode: "rss",
    category: "wire",
    url: "https://www.wsj.com/world/china",
    rss_url: "https://feeds.content.dowjones.io/public/rss/RSSWorldNews",
    paywall: true,
    enabled: true,
  },
  {
    slug: "nikkei-asia",
    display_name: "Nikkei Asia",
    country: "jp",
    lang: "en",
    tier: 1,
    mode: "rss",
    category: "wire",
    url: "https://asia.nikkei.com/",
    rss_url: "https://asia.nikkei.com/rss/feed/nar",
    paywall: true,
    enabled: true,
  },
  {
    slug: "scmp",
    display_name: "South China Morning Post",
    country: "hk",
    lang: "en",
    tier: 1,
    mode: "rss",
    category: "wire",
    url: "https://www.scmp.com/",
    rss_url: "https://www.scmp.com/rss/91/feed",
    paywall: true,
    enabled: true,
  },
  {
    slug: "cna-tw",
    display_name: "Central News Agency 中央社 · Taiwan",
    country: "tw",
    lang: "zh-tw",
    tier: 1,
    mode: "rss",
    category: "wire",
    url: "https://www.cna.com.tw/",
    rss_url: "https://feeds.feedburner.com/rsscna/politics",
    enabled: true,
  },
  {
    slug: "focus-taiwan",
    display_name: "Focus Taiwan (CNA English)",
    country: "tw",
    lang: "en",
    tier: 1,
    mode: "rss",
    category: "wire",
    url: "https://focustaiwan.tw/",
    rss_url: "https://focustaiwan.tw/RSS",
    enabled: true,
  },

  // ────────────────────────────────────────────────────────────────────
  // TIER 1 — Chinese state news (scrape required)
  // ────────────────────────────────────────────────────────────────────
  {
    slug: "xinhua",
    display_name: "新华社 Xinhua",
    country: "cn",
    lang: "zh-cn",
    tier: 1,
    mode: "scrape",
    category: "wire",
    url: "https://www.xinhuanet.com/",
    enabled: true,
    notes: "RSS deprecated. Scrape Politics/Mil/World sections.",
  },
  {
    slug: "xinhua-en",
    display_name: "Xinhua English",
    country: "cn",
    lang: "en",
    tier: 1,
    mode: "scrape",
    category: "wire",
    url: "https://english.news.cn/",
    enabled: true,
  },
  {
    slug: "people-daily",
    display_name: "人民日报 People's Daily",
    country: "cn",
    lang: "zh-cn",
    tier: 1,
    mode: "scrape",
    category: "wire",
    url: "http://paper.people.com.cn/",
    enabled: true,
  },
  {
    slug: "china-daily",
    display_name: "China Daily 中国日报",
    country: "cn",
    lang: "en",
    tier: 1,
    mode: "rss",
    category: "wire",
    url: "https://www.chinadaily.com.cn/",
    rss_url: "https://www.chinadaily.com.cn/rss/china_rss.xml",
    enabled: true,
  },
  {
    slug: "global-times-en",
    display_name: "Global Times (EN) 环球时报",
    country: "cn",
    lang: "en",
    tier: 1,
    mode: "rss",
    category: "wire",
    url: "https://www.globaltimes.cn/",
    rss_url: "https://www.globaltimes.cn/rss/outbrain.xml",
    enabled: true,
  },
  {
    slug: "global-times-cn",
    display_name: "环球时报 Global Times (CN)",
    country: "cn",
    lang: "zh-cn",
    tier: 1,
    mode: "scrape",
    category: "wire",
    url: "https://www.huanqiu.com/",
    enabled: true,
  },
  {
    slug: "pla-daily",
    display_name: "解放军报 PLA Daily",
    country: "cn",
    lang: "zh-cn",
    tier: 1,
    mode: "scrape",
    category: "defense",
    url: "http://www.81.cn/",
    enabled: true,
    notes: "Eastern Theater Command readouts here are a key Taiwan indicator.",
  },
  {
    slug: "china-mil",
    display_name: "中国军网 China Military Online",
    country: "cn",
    lang: "zh-cn",
    tier: 1,
    mode: "scrape",
    category: "defense",
    url: "http://www.81.cn/",
    enabled: true,
  },

  // ────────────────────────────────────────────────────────────────────
  // TIER 1 — Government primary sources
  // ────────────────────────────────────────────────────────────────────
  {
    slug: "mfa-prc",
    display_name: "PRC MFA 外交部 spokesperson",
    country: "cn",
    lang: "zh-cn",
    tier: 1,
    mode: "scrape",
    category: "government",
    url: "https://www.fmprc.gov.cn/web/fyrbt_673021/",
    enabled: true,
  },
  {
    slug: "tao",
    display_name: "国台办 Taiwan Affairs Office",
    country: "cn",
    lang: "zh-cn",
    tier: 1,
    mode: "scrape",
    category: "government",
    url: "https://www.gwytb.gov.cn/",
    enabled: true,
  },
  {
    slug: "mod-prc",
    display_name: "PRC MoD 国防部",
    country: "cn",
    lang: "zh-cn",
    tier: 1,
    mode: "scrape",
    category: "government",
    url: "http://www.mod.gov.cn/",
    enabled: true,
  },
  {
    slug: "tw-mnd",
    display_name: "Taiwan MND 國防部",
    country: "tw",
    lang: "zh-tw",
    tier: 1,
    mode: "scrape",
    category: "government",
    url: "https://www.mnd.gov.tw/",
    enabled: true,
    notes: "Daily PLA activity tally is a key source.",
  },
  {
    slug: "tw-mofa",
    display_name: "Taiwan MoFA 中華民國外交部",
    country: "tw",
    lang: "zh-tw",
    tier: 1,
    mode: "scrape",
    category: "government",
    url: "https://www.mofa.gov.tw/",
    enabled: true,
  },
  {
    slug: "tw-mac",
    display_name: "Taiwan MAC 大陸委員會",
    country: "tw",
    lang: "zh-tw",
    tier: 1,
    mode: "scrape",
    category: "government",
    url: "https://www.mac.gov.tw/",
    enabled: true,
  },
  {
    slug: "tw-presidential",
    display_name: "Taiwan Presidential Office",
    country: "tw",
    lang: "zh-tw",
    tier: 1,
    mode: "scrape",
    category: "government",
    url: "https://www.president.gov.tw/",
    enabled: true,
  },
  {
    slug: "us-state",
    display_name: "US Dept of State",
    country: "us",
    lang: "en",
    tier: 1,
    mode: "rss",
    category: "government",
    url: "https://www.state.gov/",
    rss_url: "https://www.state.gov/rss-feed/press-releases/feed/",
    enabled: true,
  },
  {
    slug: "ait",
    display_name: "American Institute in Taiwan",
    country: "us",
    lang: "en",
    tier: 1,
    mode: "scrape",
    category: "government",
    url: "https://www.ait.org.tw/",
    enabled: true,
  },
  {
    slug: "us-bis",
    display_name: "Bureau of Industry & Security (BIS)",
    country: "us",
    lang: "en",
    tier: 1,
    mode: "scrape",
    category: "government",
    url: "https://www.bis.doc.gov/",
    enabled: true,
    notes: "Export controls drive tech-sector coverage.",
  },
  {
    slug: "us-ofac",
    display_name: "US Treasury OFAC",
    country: "us",
    lang: "en",
    tier: 1,
    mode: "rss",
    category: "government",
    url: "https://ofac.treasury.gov/",
    rss_url: "https://ofac.treasury.gov/recent-actions/rss.xml",
    enabled: true,
  },

  // ────────────────────────────────────────────────────────────────────
  // TIER 2 — Established English media (defense, policy, finance)
  // ────────────────────────────────────────────────────────────────────
  {
    slug: "defense-news",
    display_name: "Defense News",
    country: "us",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "defense",
    url: "https://www.defensenews.com/",
    rss_url: "https://www.defensenews.com/arc/outboundfeeds/rss/",
    paywall: true,
    enabled: true,
  },
  {
    slug: "breaking-defense",
    display_name: "Breaking Defense",
    country: "us",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "defense",
    url: "https://breakingdefense.com/",
    rss_url: "https://breakingdefense.com/feed/",
    enabled: true,
  },
  {
    slug: "war-on-the-rocks",
    display_name: "War on the Rocks",
    country: "us",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "defense",
    url: "https://warontherocks.com/",
    rss_url: "https://warontherocks.com/feed/",
    enabled: true,
  },
  {
    slug: "lawfare",
    display_name: "Lawfare",
    country: "us",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "policy",
    url: "https://www.lawfaremedia.org/",
    rss_url: "https://www.lawfaremedia.org/feed",
    enabled: true,
  },
  {
    slug: "foreign-policy",
    display_name: "Foreign Policy",
    country: "us",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "policy",
    url: "https://foreignpolicy.com/",
    rss_url: "https://foreignpolicy.com/feed/",
    paywall: true,
    enabled: true,
  },
  {
    slug: "diplomat",
    display_name: "The Diplomat",
    country: "intl",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "policy",
    url: "https://thediplomat.com/",
    rss_url: "https://thediplomat.com/feed/",
    enabled: true,
  },
  {
    slug: "asia-times",
    display_name: "Asia Times",
    country: "intl",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "general",
    url: "https://asiatimes.com/",
    rss_url: "https://asiatimes.com/feed/",
    enabled: true,
  },
  {
    slug: "axios-china",
    display_name: "Axios · China",
    country: "us",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "general",
    url: "https://www.axios.com/world/china",
    rss_url: "https://api.axios.com/feed/china",
    enabled: true,
  },
  {
    slug: "semafor-asia",
    display_name: "Semafor · Asia",
    country: "us",
    lang: "en",
    tier: 2,
    mode: "scrape",
    category: "general",
    url: "https://www.semafor.com/section/asia",
    enabled: true,
  },
  {
    slug: "politico-asia",
    display_name: "Politico · Asia",
    country: "us",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "policy",
    url: "https://www.politico.eu/section/china/",
    rss_url: "https://www.politico.eu/section/china/feed/",
    paywall: true,
    enabled: true,
  },
  {
    slug: "usni-news",
    display_name: "USNI News",
    country: "us",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "defense",
    url: "https://news.usni.org/",
    rss_url: "https://news.usni.org/feed",
    enabled: true,
  },
  {
    slug: "naval-news",
    display_name: "Naval News",
    country: "intl",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "defense",
    url: "https://www.navalnews.com/",
    rss_url: "https://www.navalnews.com/feed/",
    enabled: true,
  },
  {
    slug: "janes",
    display_name: "Janes",
    country: "uk",
    lang: "en",
    tier: 2,
    mode: "scrape",
    category: "defense",
    url: "https://www.janes.com/",
    paywall: true,
    enabled: true,
  },

  // ────────────────────────────────────────────────────────────────────
  // TIER 2 — Mainland commercial / financial (RSS + scrape mix)
  // ────────────────────────────────────────────────────────────────────
  {
    slug: "caixin",
    display_name: "财新 Caixin",
    country: "cn",
    lang: "zh-cn",
    tier: 2,
    mode: "scrape",
    category: "financial",
    url: "https://www.caixin.com/",
    paywall: true,
    enabled: true,
    notes: "Selective paywall; titles + lead extract only without subscription.",
  },
  {
    slug: "caixin-global",
    display_name: "Caixin Global (EN)",
    country: "cn",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "financial",
    url: "https://www.caixinglobal.com/",
    rss_url: "https://www.caixinglobal.com/rss/",
    paywall: true,
    enabled: true,
  },
  {
    slug: "yicai",
    display_name: "第一财经 Yicai",
    country: "cn",
    lang: "zh-cn",
    tier: 2,
    mode: "scrape",
    category: "financial",
    url: "https://www.yicai.com/",
    enabled: true,
  },
  {
    slug: "yicai-global",
    display_name: "Yicai Global (EN)",
    country: "cn",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "financial",
    url: "https://www.yicaiglobal.com/",
    rss_url: "https://www.yicaiglobal.com/feed",
    enabled: true,
  },
  {
    slug: "21cbh",
    display_name: "21世纪经济报道 21st Century Business Herald",
    country: "cn",
    lang: "zh-cn",
    tier: 2,
    mode: "scrape",
    category: "financial",
    url: "https://www.21jingji.com/",
    enabled: true,
  },
  {
    slug: "eo-cn",
    display_name: "经济观察报 Economic Observer",
    country: "cn",
    lang: "zh-cn",
    tier: 2,
    mode: "scrape",
    category: "financial",
    url: "http://www.eeo.com.cn/",
    enabled: true,
  },
  {
    slug: "thepaper",
    display_name: "澎湃新闻 The Paper",
    country: "cn",
    lang: "zh-cn",
    tier: 2,
    mode: "scrape",
    category: "general",
    url: "https://www.thepaper.cn/",
    enabled: true,
  },
  {
    slug: "sina-finance",
    display_name: "新浪财经 Sina Finance",
    country: "cn",
    lang: "zh-cn",
    tier: 2,
    mode: "scrape",
    category: "financial",
    url: "https://finance.sina.com.cn/",
    enabled: true,
  },
  {
    slug: "tencent-news",
    display_name: "腾讯新闻 Tencent News",
    country: "cn",
    lang: "zh-cn",
    tier: 2,
    mode: "scrape",
    category: "general",
    url: "https://news.qq.com/",
    enabled: true,
  },
  {
    slug: "guancha",
    display_name: "观察者网 Guancha",
    country: "cn",
    lang: "zh-cn",
    tier: 2,
    mode: "scrape",
    category: "policy",
    url: "https://www.guancha.cn/",
    enabled: true,
    notes: "State-aligned commentary; useful for understanding the line.",
  },
  {
    slug: "phoenix",
    display_name: "凤凰网 Phoenix",
    country: "hk",
    lang: "zh-cn",
    tier: 2,
    mode: "scrape",
    category: "general",
    url: "https://www.ifeng.com/",
    enabled: true,
  },

  // ────────────────────────────────────────────────────────────────────
  // TIER 2 — Taiwan press
  // ────────────────────────────────────────────────────────────────────
  {
    slug: "udn",
    display_name: "聯合報 United Daily News",
    country: "tw",
    lang: "zh-tw",
    tier: 2,
    mode: "rss",
    category: "general",
    url: "https://udn.com/",
    rss_url: "https://udn.com/rssfeed/news/2/6638?ch=news",
    enabled: true,
  },
  {
    slug: "ltn",
    display_name: "自由時報 Liberty Times",
    country: "tw",
    lang: "zh-tw",
    tier: 2,
    mode: "rss",
    category: "general",
    url: "https://news.ltn.com.tw/",
    rss_url: "https://news.ltn.com.tw/rss/politics.xml",
    enabled: true,
  },
  {
    slug: "chinatimes",
    display_name: "中國時報 China Times",
    country: "tw",
    lang: "zh-tw",
    tier: 2,
    mode: "rss",
    category: "general",
    url: "https://www.chinatimes.com/",
    rss_url: "https://www.chinatimes.com/rss/politic.xml",
    enabled: true,
  },
  {
    slug: "storm-media",
    display_name: "風傳媒 Storm Media",
    country: "tw",
    lang: "zh-tw",
    tier: 2,
    mode: "rss",
    category: "general",
    url: "https://www.storm.mg/",
    rss_url: "https://www.storm.mg/feeds/all",
    enabled: true,
  },
  {
    slug: "newtalk",
    display_name: "新頭殼 NewTalk",
    country: "tw",
    lang: "zh-tw",
    tier: 2,
    mode: "rss",
    category: "general",
    url: "https://newtalk.tw/",
    rss_url: "https://newtalk.tw/rss",
    enabled: true,
  },
  {
    slug: "taipei-times",
    display_name: "Taipei Times",
    country: "tw",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "general",
    url: "https://www.taipeitimes.com/",
    rss_url: "https://www.taipeitimes.com/xml/index.rss",
    enabled: true,
  },
  {
    slug: "reporter-tw",
    display_name: "報導者 The Reporter",
    country: "tw",
    lang: "zh-tw",
    tier: 2,
    mode: "rss",
    category: "general",
    url: "https://www.twreporter.org/",
    rss_url: "https://www.twreporter.org/a/rss2.xml",
    paywall: true,
    enabled: true,
    notes: "Membership-supported; long-form investigative.",
  },

  // ────────────────────────────────────────────────────────────────────
  // TIER 2 — Hong Kong
  // ────────────────────────────────────────────────────────────────────
  {
    slug: "initium",
    display_name: "端傳媒 Initium",
    country: "hk",
    lang: "zh-tw",
    tier: 2,
    mode: "scrape",
    category: "general",
    url: "https://theinitium.com/",
    paywall: true,
    enabled: true,
    notes: "Independent, Mandarin (trad). Paywalled.",
  },
  {
    slug: "hk01",
    display_name: "HK01",
    country: "hk",
    lang: "zh-tw",
    tier: 2,
    mode: "rss",
    category: "general",
    url: "https://www.hk01.com/",
    rss_url: "https://www.hk01.com/rss",
    enabled: true,
  },
  {
    slug: "mingpao",
    display_name: "明報 Ming Pao",
    country: "hk",
    lang: "zh-tw",
    tier: 2,
    mode: "rss",
    category: "general",
    url: "https://www.mingpao.com/",
    rss_url: "https://news.mingpao.com/rss/pns/s00001.xml",
    enabled: true,
  },
  {
    slug: "hkfp",
    display_name: "Hong Kong Free Press",
    country: "hk",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "general",
    url: "https://hongkongfp.com/",
    rss_url: "https://hongkongfp.com/feed/",
    enabled: true,
  },

  // ────────────────────────────────────────────────────────────────────
  // TIER 2 — Tech industry specialist
  // ────────────────────────────────────────────────────────────────────
  {
    slug: "digitimes",
    display_name: "DigiTimes",
    country: "tw",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "tech",
    url: "https://www.digitimes.com/",
    rss_url: "https://www.digitimes.com/rss/daily.xml",
    enabled: true,
    notes: "Taiwan supply chain perspective.",
  },
  {
    slug: "trendforce",
    display_name: "TrendForce",
    country: "tw",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "tech",
    url: "https://www.trendforce.com/",
    rss_url: "https://www.trendforce.com/feed/",
    enabled: true,
  },
  {
    slug: "tech-in-asia",
    display_name: "Tech in Asia",
    country: "intl",
    lang: "en",
    tier: 2,
    mode: "rss",
    category: "tech",
    url: "https://www.techinasia.com/",
    rss_url: "https://www.techinasia.com/rss",
    paywall: true,
    enabled: true,
  },
  {
    slug: "36kr",
    display_name: "36氪 36Kr",
    country: "cn",
    lang: "zh-cn",
    tier: 2,
    mode: "scrape",
    category: "tech",
    url: "https://36kr.com/",
    enabled: true,
  },
  {
    slug: "the-information",
    display_name: "The Information",
    country: "us",
    lang: "en",
    tier: 2,
    mode: "scrape",
    category: "tech",
    url: "https://www.theinformation.com/",
    paywall: true,
    enabled: true,
    notes: "Hard paywall; titles + lead only.",
  },
  {
    slug: "semianalysis",
    display_name: "SemiAnalysis",
    country: "us",
    lang: "en",
    tier: 2,
    mode: "scrape",
    category: "tech",
    url: "https://www.semianalysis.com/",
    paywall: true,
    enabled: true,
  },

  // ────────────────────────────────────────────────────────────────────
  // TIER 3 — Think tanks, analyst newsletters
  // ────────────────────────────────────────────────────────────────────
  {
    slug: "csis",
    display_name: "CSIS",
    country: "us",
    lang: "en",
    tier: 3,
    mode: "rss",
    category: "think_tank",
    url: "https://www.csis.org/",
    rss_url: "https://www.csis.org/analysis/feed",
    enabled: true,
  },
  {
    slug: "amti",
    display_name: "AMTI · Asia Maritime Transparency Initiative",
    country: "us",
    lang: "en",
    tier: 3,
    mode: "rss",
    category: "think_tank",
    url: "https://amti.csis.org/",
    rss_url: "https://amti.csis.org/feed/",
    enabled: true,
    notes: "Satellite imagery + analysis; core PLA Navy watch source.",
  },
  {
    slug: "brookings",
    display_name: "Brookings",
    country: "us",
    lang: "en",
    tier: 3,
    mode: "rss",
    category: "think_tank",
    url: "https://www.brookings.edu/",
    rss_url: "https://www.brookings.edu/feed/",
    enabled: true,
  },
  {
    slug: "rand",
    display_name: "RAND",
    country: "us",
    lang: "en",
    tier: 3,
    mode: "rss",
    category: "think_tank",
    url: "https://www.rand.org/",
    rss_url: "https://www.rand.org/topics.xml",
    enabled: true,
  },
  {
    slug: "stimson",
    display_name: "Stimson Center",
    country: "us",
    lang: "en",
    tier: 3,
    mode: "rss",
    category: "think_tank",
    url: "https://www.stimson.org/",
    rss_url: "https://www.stimson.org/feed/",
    enabled: true,
  },
  {
    slug: "cnas",
    display_name: "CNAS · Center for a New American Security",
    country: "us",
    lang: "en",
    tier: 3,
    mode: "rss",
    category: "think_tank",
    url: "https://www.cnas.org/",
    rss_url: "https://www.cnas.org/publications/feed",
    enabled: true,
  },
  {
    slug: "cfr",
    display_name: "Council on Foreign Relations",
    country: "us",
    lang: "en",
    tier: 3,
    mode: "rss",
    category: "think_tank",
    url: "https://www.cfr.org/",
    rss_url: "https://www.cfr.org/rss-feeds",
    enabled: true,
  },
  {
    slug: "asia-society",
    display_name: "Asia Society Policy Institute",
    country: "us",
    lang: "en",
    tier: 3,
    mode: "rss",
    category: "think_tank",
    url: "https://asiasociety.org/policy-institute",
    rss_url: "https://asiasociety.org/policy-institute/feed",
    enabled: true,
  },
  {
    slug: "hudson",
    display_name: "Hudson Institute",
    country: "us",
    lang: "en",
    tier: 3,
    mode: "rss",
    category: "think_tank",
    url: "https://www.hudson.org/",
    rss_url: "https://www.hudson.org/rss",
    enabled: true,
  },
  {
    slug: "merics",
    display_name: "MERICS",
    country: "intl",
    lang: "en",
    tier: 3,
    mode: "rss",
    category: "think_tank",
    url: "https://merics.org/",
    rss_url: "https://merics.org/en/rss.xml",
    enabled: true,
  },
  {
    slug: "indsr",
    display_name: "INDSR 國防安全研究院",
    country: "tw",
    lang: "en",
    tier: 3,
    mode: "scrape",
    category: "think_tank",
    url: "https://indsr.org.tw/en",
    enabled: true,
  },
  {
    slug: "sinocism",
    display_name: "Sinocism (Bill Bishop)",
    country: "us",
    lang: "en",
    tier: 3,
    mode: "rss",
    category: "think_tank",
    url: "https://sinocism.com/",
    rss_url: "https://sinocism.com/feed",
    paywall: true,
    enabled: true,
  },
  {
    slug: "chinatalk",
    display_name: "ChinaTalk (Jordan Schneider)",
    country: "us",
    lang: "en",
    tier: 3,
    mode: "rss",
    category: "think_tank",
    url: "https://www.chinatalk.media/",
    rss_url: "https://www.chinatalk.media/feed",
    enabled: true,
  },
  {
    slug: "china-media-project",
    display_name: "China Media Project",
    country: "intl",
    lang: "en",
    tier: 3,
    mode: "rss",
    category: "think_tank",
    url: "https://chinamediaproject.org/",
    rss_url: "https://chinamediaproject.org/feed/",
    enabled: true,
  },
  {
    slug: "9dashline",
    display_name: "9DASHLINE",
    country: "uk",
    lang: "en",
    tier: 3,
    mode: "rss",
    category: "think_tank",
    url: "https://www.9dashline.com/",
    rss_url: "https://www.9dashline.com/feed",
    enabled: true,
  },
];
